# Copyright 2021 iLogtail Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release Config Server

on:
  push:
    tags:
      - v2.*

jobs:
  CI:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish Docker
        env:
          DOCKER_PUSH: true
          DOCKER_REPOSITORY: ghcr.io/jarvis-u/ilogtail/config-server
          DOCKER_TAG: ${{ github.ref_name }}
        run: |
          # Build Docker image
          docker build -t $DOCKER_REPOSITORY:$DOCKER_TAG -f config_server/service/Dockerfile config_server/service
          # Push Docker image
          docker push $DOCKER_REPOSITORY:$DOCKER_TAG

  result:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: [ CI ]
    steps:
      - name: Build Result
        run: echo "Just to make the GitHub merge button green"